/ Speed test
974~b:|/a:2/+"BR"'0:`5.txt
646~-1+*(2=-':)#^a              / second cut, below
646~*a_1+c+!b-c:&/a             / slower
646~@[(1+b)#0b;(!&/a),a;1b]?0   / faster

/ Second cut - based on insight from: https://www.reddit.com/r/adventofcode/comments/k71h6r/2020_day_05_solutions/geoawah/
974~|/a:2/+"BR"'0:`5.txt
646~-1+*(2=-':)#^a

/ First cut
f:8/2/''"BR"=+0 7^/:
974~|/a:f@0:`5.txt
646~-1+*(2=-':)#^a
